#!/usr/bin/env python3
"""Static contract tests for the public Y-DNA explorer."""

from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class YdnaExplorerTests(unittest.TestCase):
    def test_explorer_has_root_and_distance_data(self) -> None:
        page = (ROOT / "www" / "ydna.html").read_text(encoding="utf-8")
        for kit in ("325862", "B835762", "254947", "N18544", "333002", "959947", "B696189", "1002232", "B580327", "200475", "999763", "478604", "794462"):
            self.assertIn(kit, page)
        self.assertIn("'200475|B580327':[6,111]", page)
        self.assertIn("'478604':[7,111]", page)
        self.assertIn("profile:'Glasgow-2738'", page)
        self.assertIn("name:'Henry Glasgo'", page)
        self.assertIn('id="mutation-tree"', page)
        self.assertIn("Which kits sit on each confirmed SNP branch?", page)
        self.assertIn("Branch A · remains at R-FT25406", page)
        self.assertIn("Likely Glasgow-12 STR signature", page)
        self.assertIn('id="str-network"', page)
        self.assertIn("Seven-kit FT20271 STR network", page)
        self.assertNotIn("minmax(720px", page)
        self.assertIn("tested paternal lines descending from R-FT20271", page)
        self.assertIn('id="marker-placement"', page)
        self.assertIn("Where do the marker-only lines fit?", page)
        self.assertIn('id="sapp-model"', page)
        self.assertIn('class="sapp-tree-scroll"', page)
        self.assertIn('class="sapp-tree sapp-fixed"', page)
        self.assertIn('class="sapp-connectors"', page)
        self.assertIn(".sapp-tree.sapp-fixed{position:relative;height:1100px;min-width:0;overflow:hidden", page)
        self.assertIn("SAPP's reconstructed node structure", page)
        self.assertIn("Node 16", page)
        self.assertIn("Node 17", page)
        self.assertIn("Date conflicts with pedigree", page)
        self.assertIn("Adjusted-GD path:", page)
        self.assertIn("Control check passed.", page)
        self.assertIn("794462</code> ·", page)
        self.assertIn("GD 0/111", page)
        self.assertIn("B835762</code> ·", page)
        self.assertIn("GD 2/37", page)
        self.assertIn("N18544</code> ·", page)
        self.assertIn("GD 4/67", page)
        self.assertIn("DYS714=26", page)
        self.assertIn("'200475|794462':[0,111]", page)
        self.assertIn("All pairwise genetic distances", page)
        self.assertIn("'200475|959947':[1,111]", page)
        self.assertIn("'478604|999763':[1,111]", page)
        self.assertIn("the four closely related Glasgow-12 kits were collapsed", page)
        self.assertIn("1431 CE", page)
        self.assertIn("1199–1608", page)
        self.assertIn("1583 CE", page)
        self.assertIn("1387–1728", page)
        self.assertIn("Glasgow-951 ↗", page)
        self.assertIn("Glasgow-2738 ↗", page)
        self.assertIn("Glasgow-591 ↗", page)
        self.assertIn("Jeremiah Glasgo (Glasgo-23)", page)
        self.assertIn("Glasgow-12 ↗", page)
        self.assertIn("FT25406 → FT20271 → FTE32242", page)
        self.assertIn('id="match-neighbourhood"', page)
        self.assertIn("Every Y-111 match to Alexander's kit", page)
        self.assertIn("FT20271 / FTE32242 (6)", page)
        self.assertIn("Wm Farrier and Susanna Abell line", page)
        self.assertIn("Henry Ferrier, born c.1758", page)
        self.assertIn("8 of 17", page)
        self.assertIn("DYS19=15 · DYS456=16 · DYS712=19", page)
        self.assertIn("12648194 A→G", page)
        self.assertIn("26534797 C→G", page)
        self.assertIn("whose named mutation is C→A", page)
        self.assertIn("Possible shared off-tree variant", page)
        self.assertIn("FT6135 C→T", page)
        self.assertIn("Branch-inheritance test at Robert Glasgow-12", page)
        self.assertIn("FT6135 fails a clean three-son inheritance test", page)
        self.assertIn("Pedigree audit changes the interpretation:", page)
        self.assertIn("Documented William Glasgow branch", page)
        self.assertIn("43290879-Nebraska-204066-0005.jpg", page)
        self.assertIn("Glasgow-1877", page)
        self.assertIn('id="snp-splits"', page)
        self.assertIn("15/15 covered", page)
        self.assertIn("variantSplitFromB580327", page)
        self.assertIn("FT25406, FT16394, FT18145 and FT26594", page)
        self.assertIn("FT20271 · FGC5690 · FT16542", page)
        self.assertIn("5 · avg 3", page)
        self.assertIn("identical across the displayed Y-111 panel (GD 0)", page)
        self.assertIn("all 829 exported STR/FTY fields", page)
        self.assertIn("Two different “closest” results", page)
        self.assertIn("DYS712 mutates rapidly", page)
        self.assertIn("KIT 999763 · BIG Y", page)
        self.assertIn("KIT 478604 · BIG Y", page)
        self.assertIn("James M. Glasgow (Glasgow-193)", page)
        self.assertIn("William Allen Glasgow (Glasgow-2182)", page)
        self.assertIn("Samuel Lyle Glasgow (Glasgow-192)", page)
        self.assertIn("profile:'Glasgo-21',match:'linked'", page)
        self.assertIn("profile:'Glasgow-12',match:'linked'", page)
        self.assertIn("200475 + 999763 + 478604 + 794462", page)
        self.assertIn('class="nav-toggle"', page)
        self.assertIn('aria-controls="ydna-nav"', page)
        self.assertIn('class="root-groups"', page)
        self.assertIn('class="section-disclosure"', page)
        self.assertIn('class="section-disclosure compare-disclosure"', page)
        self.assertIn('class="section-disclosure default-open" open', page)
        self.assertIn('class="str-network-panel card-disclosure default-open"', page)
        self.assertIn('root-group-disclosure', page)
        self.assertNotIn('Profile evidence', page)
        self.assertIn('id="root-search"', page)
        self.assertIn('data-view-mode="overview"', page)
        self.assertIn('data-view-mode="full"', page)
        self.assertIn('class="compare-root"', page)
        self.assertIn('id="share-comparison"', page)
        self.assertIn("searchParams.set('kitA'", page)
        self.assertIn("searchParams.set('kitB'", page)
        self.assertIn("initDistanceMatrix", page)
        self.assertIn('class="matrix-scroll-hint"', page)
        self.assertIn('class="matrix-selection"', page)
        self.assertIn('href="#match-neighbourhood"', page)
        self.assertIn('href="#next-steps"', page)
        self.assertIn('id="next-steps"', page)
        self.assertIn("Upgrade kit <code>254947</code> from Y-111 to Big Y-700", page)
        self.assertIn("Request the full Big Y bundle for kit <code>1002232</code>", page)
        self.assertIn("Minimum useful “full bundle” request:", page)
        self.assertIn("A BAM file is not needed for the first-pass questions", page)
        self.assertIn('class="inline-disclosure"', page)
        self.assertLess(page.index('class="distance-wrap"'), page.index('class="inline-disclosure"'))
        self.assertIn('<details class="inheritance-audit">', page)
        self.assertIn('class="inline-disclosure block-tree-notes"', page)
        self.assertLess(page.index('id="str-network"'), page.index('class="inline-disclosure block-tree-notes"'))
        self.assertLess(page.index('id="str-evidence-title"'), page.index('id="inheritance-title"'))
        self.assertIn('class="back-to-top"', page)
        self.assertIn("updateActiveNav", page)
        self.assertIn("Confirmed Big Y", page)
        self.assertIn("Needs Big Y", page)
        self.assertLess(page.index('id="roots"'), page.index('id="compare"'))
        self.assertLess(page.index('id="roots"'), page.index('id="snp-splits"'))
        self.assertLess(page.index('id="roots"'), page.index('id="match-neighbourhood"'))
        self.assertNotIn('href="people/', page)
        self.assertIn("R-FTE32242 is downstream of R-FT20271", page)
        self.assertIn("Directional SNP differences", page)
        for living_name in ("Karl Glasgow", "Rod Dale Glasgow", "Gerald Neumann Glasgow", "Craig Linn Glasgow", "Nathan Jacobs", "David Lee Glasgow", "Christopher Dale Glasgow", "Robert Brown", "Brian Wilson", "Jerry Glasgo", "John Edward Farrier", "Jason Phillips", "Michael B Glasgow", "Jack Glasgow", "Roger Allan Glasgow", "Christopher Stephen FARRIER", "J P FARRIER"):
            self.assertNotIn(living_name, page)

    def test_home_and_discovery_links_exist(self) -> None:
        self.assertIn('href="ydna.html"', (ROOT / "www" / "index.html").read_text(encoding="utf-8"))
        self.assertIn("/ydna.html", (ROOT / "www" / "sitemap.xml").read_text(encoding="utf-8"))
        self.assertIn("/ydna.html", (ROOT / "www" / "llms.txt").read_text(encoding="utf-8"))

    def test_deep_timeline_preserves_unplaced_match_boundary(self) -> None:
        timeline = (ROOT / "www" / "timeline.html").read_text(encoding="utf-8")
        self.assertIn("three Farrier/Ferrier Y-111 lines at GD 4, 4 and 5", timeline)
        self.assertIn("not drawn inside FT20271", timeline)
        self.assertIn("R-FTA30932, a different named branch", timeline)


if __name__ == "__main__":
    unittest.main()
